In [ ]:
import pandas as pd
import numpy as np
import json

import tensorflow as tf
import os

In [ ]:
pd.set_option('display.max_columns', 60)
# pd.set_option('display.max_rows', 11)

## Dummy Data

### Feature Selection

In [ ]:
fbref = [
    # index
    'Player',
    # post-match player information/stats
    "Pos",
    "Age",
    "Min",
    # pre-match player information/stats
    'standard - Nation',
    'standard - Pos',
    'standard - Age',
    'standard - MP',
    'standard - Playing Time - Starts',
    'standard - Playing Time - Min',
    'standard - Playing Time - 90s',
    'standard - Performance - Gls',
    'standard - Performance - Ast',
    'standard - Performance - G-PK',
    'standard - Performance - PK',
    'standard - Performance - PKatt',
    'standard - Performance - CrdY',
    'standard - Performance - CrdR',
    'standard - Per 90 Minutes - Gls',
    'standard - Per 90 Minutes - Ast',
    'standard - Per 90 Minutes - G+A',
    'standard - Per 90 Minutes - G-PK',
    'standard - Per 90 Minutes - G+A-PK',
    'standard - Expected - xG',
    'standard - Expected - npxG',
    'standard - Expected - xAG',
    'standard - Expected - npxG+xAG',
    'standard - Per 90 Minutes - xG',
    'standard - Per 90 Minutes - xAG',
    'standard - Per 90 Minutes - xG+xAG',
    'standard - Per 90 Minutes - npxG',
    'standard - Per 90 Minutes - npxG+xAG',
    'keeper - Nation',
    'keeper - Pos',
    'keeper - Age',
    'keeper - Playing Time - MP',
    'keeper - Playing Time - Starts',
    'keeper - Playing Time - Min',
    'keeper - Playing Time - 90s',
    'keeper - Performance - GA',
    'keeper - Performance - GA90',
    'keeper - Performance - SoTA',
    'keeper - Performance - Saves',
    'keeper - Performance - Save%',
    'keeper - Performance - W',
    'keeper - Performance - D',
    'keeper - Performance - L',
    'keeper - Performance - CS',
    'keeper - Performance - CS%',
    'keeper - Penalty Kicks - PKatt',
    'keeper - Penalty Kicks - PKA',
    'keeper - Penalty Kicks - PKsv',
    'keeper - Penalty Kicks - PKm',
    'keeper - Penalty Kicks - Save%',
    'keeper_adv - Nation',
    'keeper_adv - Pos',
    'keeper_adv - Age',
    'keeper_adv - 90s',
    'keeper_adv - Goals - GA',
    'keeper_adv - Goals - PKA',
    'keeper_adv - Goals - FK',
    'keeper_adv - Goals - CK',
    'keeper_adv - Goals - OG',
    'keeper_adv - Expected - PSxG',
    'keeper_adv - Expected - PSxG/SoT',
    'keeper_adv - Expected - PSxG+/-',
    'keeper_adv - Expected - /90',
    'keeper_adv - Launched - Cmp',
    'keeper_adv - Launched - Att',
    'keeper_adv - Launched - Cmp%',
    'keeper_adv - Passes - Att',
    'keeper_adv - Passes - Thr',
    'keeper_adv - Passes - Launch%',
    'keeper_adv - Passes - AvgLen',
    'keeper_adv - Goal Kicks - Att',
    'keeper_adv - Goal Kicks - Launch%',
    'keeper_adv - Goal Kicks - AvgLen',
    'keeper_adv - Crosses - Opp',
    'keeper_adv - Crosses - Stp',
    'keeper_adv - Crosses - Stp%',
    'keeper_adv - Sweeper - #OPA',
    'keeper_adv - Sweeper - #OPA/90',
    'keeper_adv - Sweeper - AvgDist',
    'shooting - Nation',
    'shooting - Pos',
    'shooting - Age',
    'shooting - 90s',
    'shooting - Standard - Gls',
    'shooting - Standard - Sh',
    'shooting - Standard - SoT',
    'shooting - Standard - SoT%',
    'shooting - Standard - Sh/90',
    'shooting - Standard - SoT/90',
    'shooting - Standard - G/Sh',
    'shooting - Standard - G/SoT',
    'shooting - Standard - Dist',
    'shooting - Standard - FK',
    'shooting - Standard - PK',
    'shooting - Standard - PKatt',
    'shooting - Expected - xG',
    'shooting - Expected - npxG',
    'shooting - Expected - npxG/Sh',
    'shooting - Expected - G-xG',
    'shooting - Expected - np:G-xG',
    'passing - Nation',
    'passing - Pos',
    'passing - Age',
    'passing - 90s',
    'passing - Ast',
    'passing - xAG',
    'passing - xA',
    'passing - A-xAG',
    'passing - KP',
    'passing - 1/3',
    'passing - PPA',
    'passing - CrsPA',
    'passing - Prog',
    'passing - Total - Cmp',
    'passing - Total - Att',
    'passing - Total - Cmp%',
    'passing - Total - TotDist',
    'passing - Total - PrgDist',
    'passing - Short - Cmp',
    'passing - Short - Att',
    'passing - Short - Cmp%',
    'passing - Medium - Cmp',
    'passing - Medium - Att',
    'passing - Medium - Cmp%',
    'passing - Long - Cmp',
    'passing - Long - Att',
    'passing - Long - Cmp%',
    'passing_types - Nation',
    'passing_types - Pos',
    'passing_types - Age',
    'passing_types - 90s',
    'passing_types - Att',
    'passing_types - Pass Types - Live',
    'passing_types - Pass Types - Dead',
    'passing_types - Pass Types - FK',
    'passing_types - Pass Types - TB',
    'passing_types - Pass Types - Sw',
    'passing_types - Pass Types - Crs',
    'passing_types - Pass Types - TI',
    'passing_types - Pass Types - CK',
    'passing_types - Corner Kicks - In',
    'passing_types - Corner Kicks - Out',
    'passing_types - Corner Kicks - Str',
    'passing_types - Outcomes - Cmp',
    'passing_types - Outcomes - Off',
    'passing_types - Outcomes - Blocks',
    'gca - Nation',
    'gca - Pos',
    'gca - Age',
    'gca - 90s',
    'gca - SCA - SCA',
    'gca - SCA - SCA90',
    'gca - SCA Types - PassLive',
    'gca - SCA Types - PassDead',
    'gca - SCA Types - Drib',
    'gca - SCA Types - Sh',
    'gca - SCA Types - Fld',
    'gca - SCA Types - Def',
    'gca - GCA - GCA',
    'gca - GCA - GCA90',
    'gca - GCA Types - PassLive',
    'gca - GCA Types - PassDead',
    'gca - GCA Types - Drib',
    'gca - GCA Types - Sh',
    'gca - GCA Types - Fld',
    'gca - GCA Types - Def',
    'defense - Nation',
    'defense - Pos',
    'defense - Age',
    'defense - 90s',
    'defense - Int',
    'defense - Tkl+Int',
    'defense - Clr',
    'defense - Err',
    'defense - Tackles - Tkl',
    'defense - Tackles - TklW',
    'defense - Tackles - Def 3rd',
    'defense - Tackles - Mid 3rd',
    'defense - Tackles - Att 3rd',
    'defense - Vs Dribbles - Tkl',
    'defense - Vs Dribbles - Att',
    'defense - Vs Dribbles - Tkl%',
    'defense - Vs Dribbles - Past',
    'defense - Blocks - Blocks',
    'defense - Blocks - Sh',
    'defense - Blocks - Pass',
    'possession - Nation',
    'possession - Pos',
    'possession - Age',
    'possession - 90s',
    'possession - Touches - Touches',
    'possession - Touches - Def Pen',
    'possession - Touches - Def 3rd',
    'possession - Touches - Mid 3rd',
    'possession - Touches - Att 3rd',
    'possession - Touches - Att Pen',
    'possession - Touches - Live',
    'possession - Dribbles - Succ',
    'possession - Dribbles - Att',
    'possession - Dribbles - Succ%',
    'possession - Dribbles - Mis',
    'possession - Dribbles - Dis',
    'possession - Receiving - Rec',
    'possession - Receiving - Prog',
    'playing_time - Nation',
    'playing_time - Pos',
    'playing_time - Age',
    'playing_time - MP',
    'playing_time - Playing Time - Min',
    'playing_time - Playing Time - Mn/MP',
    'playing_time - Playing Time - Min%',
    'playing_time - Playing Time - 90s',
    'playing_time - Starts - Starts',
    'playing_time - Starts - Mn/Start',
    'playing_time - Starts - Compl',
    'playing_time - Subs - Subs',
    'playing_time - Subs - Mn/Sub',
    'playing_time - Subs - unSub',
    'playing_time - Team Success - PPM',
    'playing_time - Team Success - onG',
    'playing_time - Team Success - onGA',
    'playing_time - Team Success - +/-',
    'playing_time - Team Success - +/-90',
    'playing_time - Team Success - On-Off',
    'playing_time - Team Success (xG) - onxG',
    'playing_time - Team Success (xG) - onxGA',
    'playing_time - Team Success (xG) - xG+/-',
    'playing_time - Team Success (xG) - xG+/-90',
    'playing_time - Team Success (xG) - On-Off',
    'misc - Nation',
    'misc - Pos',
    'misc - Age',
    'misc - 90s',
    'misc - Performance - CrdY',
    'misc - Performance - CrdR',
    'misc - Performance - 2CrdY',
    'misc - Performance - Fls',
    'misc - Performance - Fld',
    'misc - Performance - Off',
    'misc - Performance - Crs',
    'misc - Performance - Int',
    'misc - Performance - TklW',
    'misc - Performance - PKwon',
    'misc - Performance - PKcon',
    'misc - Performance - OG',
    'misc - Performance - Recov',
    'misc - Aerial Duels - Won',
    'misc - Aerial Duels - Lost',
    'misc - Aerial Duels - Won%',
]

In [ ]:
len(fbref)

253

In [ ]:
DATA_SAMPLE = 100
PLAYERS = 11

In [ ]:
POSITION_CHOICES = [
    "GK", 
    "DF", "CB", "FB", "LB", "RB", "WB",
    "MF", "DM", "CM", "LM", "RM", "WM", "AM",
    "FW", "LW", "RW"
]

### Data

In [ ]:
def get_random_player_values(feature_columns: list = fbref, num_sample: int = 30):
    feature_dimension = len(feature_columns)
    teams = ["Home", "Away"]
    players = [f"Player {i}" for i in range(1, 12)]
    per_player_values = []

    first_level = np.array([[team] * 11 * feature_dimension for team in teams]).flatten()
    second_level = np.array([[player] * feature_dimension for player in players] * 2).flatten()
    third_level = [feature for feature in feature_columns] * 11 * 2

    # ref: https://stackoverflow.com/questions/67148870/how-to-create-a-pandas-dataframe-with-multiindex-columns-with-several-level-0
    dummy_data = np.abs(np.random.randn(num_sample, 2 * 11 * feature_dimension))
    columns = pd.MultiIndex.from_arrays([
        first_level,
        second_level,
        third_level
    ], names=["Club", "Player", "Statistic"])
    df = pd.DataFrame(
        dummy_data,
        columns=columns,
    )

    dummy_Y = [[np.random.randint(5), np.random.randint(5)] for sample in range(num_sample)]
    columns_Y = pd.MultiIndex.from_arrays([
        ["Home", "Away"],
        ["----", "----"],
        ["Score", "Score"]
    ])
    df_Y = pd.DataFrame(
        dummy_Y,
        columns=columns_Y
    )

    return pd.concat([df, df_Y], axis=1)

In [ ]:
ATTRIBUTE_DIMENSION = 20
df_test = get_random_player_values(fbref[:ATTRIBUTE_DIMENSION])

In [ ]:
df_test.head(2)

Club           Home                                                  \
Player     Player 1
Statistic    Player       Pos       Age       Min standard - Nation
0          1.274392  0.184533  0.251661  0.440113          0.276776
1          0.237617  0.390054  0.383636  0.472280          1.041909

Club                                                   \
Player
Statistic standard - Pos standard - Age standard - MP
0               0.337331       0.331922      0.652587
1               0.373121       0.033766      0.042163

Club                                                                      ...  \
Player                                                                    ...
Statistic standard - Playing Time - Starts standard - Playing Time - Min  ...
0                                 0.845367                      0.216467  ...
1                                 1.157946                      1.982208  ...

Club                              Away                                \
Player                       Player 11
Statistic standard - Performance - Ast standard - Performance - G-PK
0                             0.435502                      0.620961
1                             0.330738                      0.110805

Club                                                                  \
Player
Statistic standard - Performance - PK standard - Performance - PKatt
0                            0.593856                       0.779377
1                            1.959187                       0.378540

Club                                                                   \
Player
Statistic standard - Performance - CrdY standard - Performance - CrdR
0                              0.427247                      1.009182
1                              1.179908                      0.832855

Club                                                                       \
Player
Statistic standard - Per 90 Minutes - Gls standard - Per 90 Minutes - Ast
0                                1.537792                        2.337339
1                                0.953413                        0.426671

Club       Home  Away
Player     ----  ----
Statistic Score Score
0             4     3
1             4     3

[2 rows x 442 columns]

In [ ]:
df_test.loc[:, pd.IndexSlice[:, "Player 1"]].head(3)

Club           Home                                                  \
Player     Player 1
Statistic    Player       Pos       Age       Min standard - Nation
0          1.274392  0.184533  0.251661  0.440113          0.276776
1          0.237617  0.390054  0.383636  0.472280          1.041909
2          0.053277  0.330896  2.047975  0.202479          0.756089

Club                                                   \
Player
Statistic standard - Pos standard - Age standard - MP
0               0.337331       0.331922      0.652587
1               0.373121       0.033766      0.042163
2               0.502802       0.040013      1.647814

Club                                                                      ...  \
Player                                                                    ...
Statistic standard - Playing Time - Starts standard - Playing Time - Min  ...
0                                 0.845367                      0.216467  ...
1                                 1.157946                      1.982208  ...
2                                 0.170346                      0.558988  ...

Club                               Away                               \
Player                         Player 1
Statistic standard - Playing Time - 90s standard - Performance - Gls
0                              0.456917                     0.630510
1                              0.799717                     0.844329
2                              0.246665                     0.011171

Club                                                                  \
Player
Statistic standard - Performance - Ast standard - Performance - G-PK
0                             0.546931                      0.308071
1                             1.285227                      0.938118
2                             0.731246                      0.010122

Club                                                                  \
Player
Statistic standard - Performance - PK standard - Performance - PKatt
0                            0.476495                       2.563838
1                            0.276851                       0.018892
2                            0.019639                       0.417210

Club                                                                   \
Player
Statistic standard - Performance - CrdY standard - Performance - CrdR
0                              0.065294                      0.436970
1                              0.152244                      0.317684
2                              0.223293                      0.818015

Club
Player
Statistic standard - Per 90 Minutes - Gls standard - Per 90 Minutes - Ast
0                                1.136490                        1.045108
1                                1.814139                        0.791083
2                                1.500935                        0.081574

[3 rows x 40 columns]

In [ ]:
# ref: https://stackoverflow.com/questions/51502959/python-pandas-query-a-multiindex-column
df_test.loc[:5, pd.IndexSlice["Home", ["Player 1", "Player 2"]]]

Club           Home                                                  \
Player     Player 1
Statistic    Player       Pos       Age       Min standard - Nation
0          1.274392  0.184533  0.251661  0.440113          0.276776
1          0.237617  0.390054  0.383636  0.472280          1.041909
2          0.053277  0.330896  2.047975  0.202479          0.756089
3          0.547236  0.346334  0.474025  0.374353          1.173501
4          1.194990  0.347754  0.294990  1.441657          0.033718
5          0.528935  1.230341  0.649337  0.978129          0.707317

Club                                                   \
Player
Statistic standard - Pos standard - Age standard - MP
0               0.337331       0.331922      0.652587
1               0.373121       0.033766      0.042163
2               0.502802       0.040013      1.647814
3               1.516613       1.295847      0.503798
4               1.100664       0.328083      1.339552
5               1.266682       0.466350      1.028687

Club                                                                      ...  \
Player                                                                    ...
Statistic standard - Playing Time - Starts standard - Playing Time - Min  ...
0                                 0.845367                      0.216467  ...
1                                 1.157946                      1.982208  ...
2                                 0.170346                      0.558988  ...
3                                 0.574801                      0.279458  ...
4                                 0.529595                      0.613247  ...
5                                 0.654686                      0.334455  ...

Club                                                                  \
Player                         Player 2
Statistic standard - Playing Time - 90s standard - Performance - Gls
0                              0.504859                     1.574169
1                              0.446041                     1.021960
2                              0.466261                     0.431680
3                              0.258586                     1.120896
4                              0.008284                     1.377778
5                              0.030851                     0.482291

Club                                                                  \
Player
Statistic standard - Performance - Ast standard - Performance - G-PK
0                             1.768557                      1.971132
1                             1.341285                      0.022141
2                             1.717188                      1.512186
3                             0.821591                      0.634271
4                             1.495102                      0.605974
5                             1.148909                      0.364718

Club                                                                  \
Player
Statistic standard - Performance - PK standard - Performance - PKatt
0                            1.306475                       0.831650
1                            1.299767                       0.774288
2                            1.941891                       1.228503
3                            0.355946                       0.727879
4                            0.222875                       1.292318
5                            1.647929                       0.608388

Club                                                                   \
Player
Statistic standard - Performance - CrdY standard - Performance - CrdR
0                              0.298336                      0.030592
1                              0.389973                      1.112898
2                              1.203390                      0.938776
3                              0.127073                      0.450658
4                              0.819301                      1.699979
5                              0.292437                      0.284007

Club
Player
Statistic standard - Per 90 Minutes - Gls standard - Per 90 Minutes - Ast
0                                0.185303                        0.007845
1                                0.707992                        0.952780
2                                0.074890                        0.564746
3                                1.193752                        0.039474
4                                0.359206                        0.051336
5                                0.619095                        0.610091

[6 rows x 40 columns]

In [ ]:
home = df_test.loc[:, pd.IndexSlice["Home"]]
home_players = home.columns.get_level_values("Player").unique()
home.groupby(level="Statistic", axis=1).mean().values.shape[1]
standard_col = [col for col in home.columns.get_level_values(level='Statistic') if 'standard' in col]

home.loc[:3, pd.IndexSlice[["Player 1", "Player 4", "Player 3"], standard_col]]

Player             Player 1                                              \
Statistic standard - Nation standard - Pos standard - Age standard - MP
0                  0.276776       0.337331       0.331922      0.652587
1                  1.041909       0.373121       0.033766      0.042163
2                  0.756089       0.502802       0.040013      1.647814
3                  1.173501       1.516613       1.295847      0.503798

Player                                                                    \
Statistic standard - Playing Time - Starts standard - Playing Time - Min
0                                 0.845367                      0.216467
1                                 1.157946                      1.982208
2                                 0.170346                      0.558988
3                                 0.574801                      0.279458

Player                                                                \
Statistic standard - Playing Time - 90s standard - Performance - Gls
0                              1.167089                     1.409897
1                              0.372479                     0.815505
2                              1.035125                     0.210683
3                              0.537632                     1.180906

Player                                                                ...  \
Statistic standard - Performance - Ast standard - Performance - G-PK  ...
0                             0.667445                      0.747740  ...
1                             0.064953                      0.606287  ...
2                             0.079680                      0.755339  ...
3                             1.798689                      1.330088  ...

Player                         Player 3                               \
Statistic standard - Playing Time - 90s standard - Performance - Gls
0                              0.170237                     0.321656
1                              1.452298                     0.350826
2                              1.643570                     0.888821
3                              0.473993                     2.262523

Player                                                                \
Statistic standard - Performance - Ast standard - Performance - G-PK
0                             1.586664                      0.779966
1                             0.544382                      0.485317
2                             0.392213                      0.137188
3                             0.201163                      0.000608

Player                                                                \
Statistic standard - Performance - PK standard - Performance - PKatt
0                            0.139712                       0.630891
1                            0.204123                       0.039065
2                            1.609199                       1.895059
3                            0.563637                       1.779890

Player                                                                 \
Statistic standard - Performance - CrdY standard - Performance - CrdR
0                              0.757619                      0.282410
1                              1.330752                      0.491434
2                              0.711263                      0.177062
3                              1.722567                      0.626207

Player
Statistic standard - Per 90 Minutes - Gls standard - Per 90 Minutes - Ast
0                                1.359871                        2.203965
1                                1.092755                        0.399967
2                                0.585598                        0.986662
3                                0.407615                        0.893343

[4 rows x 48 columns]

### Input & Output

In [ ]:
df_Y_test = df_test.iloc[:, -2:]
df_X_test = df_test.iloc[:, :-2]

In [ ]:
from typing import Tuple

def FT_Preprocess_Input(
    df_inputs: pd.DataFrame,
    to_tensor=False
) -> Tuple[pd.DataFrame, np.ndarray, pd.DataFrame, np.ndarray]:
    home = df_inputs.loc[:, pd.IndexSlice["Home"]]
    away = df_inputs.loc[:, pd.IndexSlice["Away"]]
    
    home_players_columns = home.columns.get_level_values("Player").unique()
    away_players_columns = home.columns.get_level_values("Player").unique()

    home_stats_average = home.groupby(level="Statistic", axis=1).mean().values
    away_stats_average = away.groupby(level="Statistic", axis=1).mean().values

    # # process vector values per player for home team
    # for player in home_players_columns:
    #   player_stats = home.loc[:, pd.IndexSlice[player]]
    #   player_stats = np.array(player_stats)
    #   team_stats = team_embedding(player_stats, home_stats_average)
    #   opposition_stats = opposition_embedding(player_stats, away_stats_average)

    # # process vector values per player for away team
    # for player in away_players_columns:
    #   player_stats = away.loc[:, pd.IndexSlice[player]]
    #   player_stats = np.array(player_stats)
    #   team_stats = team_embedding(player_stats, away_stats_average)
    #   opposition_stats = opposition_embedding(player_stats, home_stats_average)
    
    if to_tensor == True:
        home = tf.convert_to_tensor(home, dtype=tf.float32)
        home_stats_average = tf.convert_to_tensor(home_stats_average, dtype=tf.float32)
        away = tf.convert_to_tensor(away, dtype=tf.float32)
        away_stats_average = tf.convert_to_tensor(away_stats_average, dtype=tf.float32)
        ft_preprocessed_input = (home, home_stats_average, away, away_stats_average)
        return ft_preprocessed_input

    ft_preprocessed_input = (home, home_stats_average, away, away_stats_average)
    return ft_preprocessed_input

In [ ]:
ft_preprocessed_inputs = FT_Preprocess_Input(df_X_test)
home, home_stats_average, away, away_stats_average = ft_preprocessed_inputs

In [ ]:
print(FT_Preprocess_Input(df_test)[0].shape)
print(FT_Preprocess_Input(df_test)[1].shape)
print(FT_Preprocess_Input(df_test)[2].shape)
print(FT_Preprocess_Input(df_test)[3].shape)

(30, 221)
(30, 21)
(30, 221)
(30, 21)

In [ ]:
home.loc[:2, pd.IndexSlice["Player 1"]]
home.iloc[:2, :3]

Player     Player 1
Statistic    Player       Pos       Age
0          1.274392  0.184533  0.251661
1          0.237617  0.390054  0.383636

In [ ]:
tf.add_n([tf.Variable([1, 2, 3]), tf.Variable([5, 5, 5]), tf.Variable([10, 11, 12])])

In [ ]:
def FT_Preprocess_Output(
    df_Y: pd.DataFrame,
    to_tensor=False
) -> pd.DataFrame:

    home_score = df_Y.columns[0]
    away_score = df_Y.columns[1]
    
    new_cols = pd.MultiIndex.from_arrays([
        ["Home Result", "Home Result", "Home Result"],
        ["", "", ""],
        ["Win", "Draw", "Lost"],
    ], names=df_Y.columns.names)
    df_home_result = pd.DataFrame(columns=new_cols)

    df_home_result[new_cols[0]] = (df_Y[home_score] > df_Y[away_score]).apply(lambda x: 1 if x is True else 0)
    df_home_result[new_cols[1]]= (df_Y[home_score] == df_Y[away_score]).apply(lambda x: 1 if x is True else 0)
    df_home_result[new_cols[2]]= (df_Y[home_score] < df_Y[away_score]).apply(lambda x: 1 if x is True else 0)

    if to_tensor == True:
        return tf.convert_to_tensor(df_Y), tf.convert_to_tensor(df_home_result)

    return df_Y, df_home_result

In [ ]:
FT_Preprocess_Output(df_Y_test)[1].head(2)

Club      Home Result
Player
Statistic         Win Draw Lost
0                   1    0    0
1                   1    0    0

## Data Acquisition & Train-Test Split

In [ ]:
LEAGUES = ["Premier-League", "Serie-A", "La-Liga", "Ligue-1", "Bundesliga"]
INDEX_START_SCRAPPING = [197, 200, 191, 210, 163]

DATA_DIR = "/content/drive/MyDrive/Projects/Football Team Simulation/data"
SAVE_DIR = os.path.join(DATA_DIR, "raw/Premier-League/2022-2023_Matches")
TABLE_REF_PATH = os.path.join(DATA_DIR, "raw/Premier-League/table_ref.csv")
TRANSFORM_DIR = os.path.join(DATA_DIR, "transformed")
DICTIONARIES_PATH = os.path.join(DATA_DIR, "raw/dictionaries.json")

In [ ]:
LEAGUE_CODE = json.load(open(f"{DATA_DIR}/raw/dictionaries.json", mode='rb'))["LEAGUE_CODE"]
LEAGUE_LINK = json.load(open(f"{DATA_DIR}/raw/dictionaries.json", mode='rb'))["LEAGUE_LINK"]
TEAM_CODE = json.load(open(f"{DATA_DIR}/raw/dictionaries.json", mode='rb'))["TEAM_CODE"]
TEAM_DISPLAY = json.load(open(f"{DATA_DIR}/raw/dictionaries.json", mode='rb'))["TEAM_DISPLAY"]

In [ ]:
PREMIER_LEAGUE_TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[0]}/table_ref.csv")
SERIE_A_TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[1]}/table_ref.csv")
LA_LIGA_TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[2]}/table_ref.csv")
LIGUE_1_TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[3]}/table_ref.csv")
BUNDESLIGA_TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[4]}/table_ref.csv")

table_ref = pd.read_csv(BUNDESLIGA_TABLE_REF_PATH, index_col=0)

In [ ]:
cond = table_ref["Score"].notnull()

In [ ]:
# since the start of the data scrapping is at Crystal Palace vs Manchester United
# then start from there, whose index is 197
cond2 = table_ref.index >= 163

df_recorded_matches = table_ref.loc[cond & cond2, :]

In [ ]:
df_recorded_matches.head(10)

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes,Match Report Link,League
163,19.0,Sat,2023-02-04,15:30,Eint Frankfurt,2.2,3–0,0.9,Hertha BSC,49500.0,Deutsche Bank Park,Robert Hartmann,Match Report,NaN,/en/matches/4e460d5f/Eintracht-Frankfurt-Herth...,Bundesliga
164,19.0,Sat,2023-02-04,15:30,Bochum,2.7,5–2,0.9,Hoffenheim,23700.0,Vonovia Ruhrstadion,Bastian Dankert,Match Report,NaN,/en/matches/66ad90ae/Bochum-Hoffenheim-Februar...,Bundesliga
165,19.0,Sat,2023-02-04,15:30,Köln,0.8,0–0,1.3,RB Leipzig,NaN,RheinEnergieSTADION,Martin Petersen,Match Report,NaN,/en/matches/7e5eb5e7/Koln-RB-Leipzig-February-...,Bundesliga
166,19.0,Sat,2023-02-04,15:30,Dortmund,1.9,5–1,0.4,Freiburg,81365.0,Signal Iduna Park,Robert Schröder,Match Report,NaN,/en/matches/85e9a74e/Dortmund-Freiburg-Februar...,Bundesliga
167,19.0,Sat,2023-02-04,15:30,Union Berlin,1.1,2–1,1.3,Mainz 05,22012.0,Stadion An der Alten Försterei,Florian Badstübner,Match Report,NaN,/en/matches/b4d8e07a/Union-Berlin-Mainz-05-Feb...,Bundesliga
168,19.0,Sat,2023-02-04,18:30,M'Gladbach,1.1,0–0,1.0,Schalke 04,54042.0,Stadion im Borussia-Park,Deniz Aytekin,Match Report,NaN,/en/matches/bd090272/Monchengladbach-Schalke-0...,Bundesliga
169,19.0,Sun,2023-02-05,15:30,Stuttgart,1.3,0–2,0.5,Werder Bremen,47700.0,Mercedes-Benz Arena,Frank Willenborg,Match Report,NaN,/en/matches/8668a4af/Stuttgart-Werder-Bremen-F...,Bundesliga
170,19.0,Sun,2023-02-05,17:30,Wolfsburg,2.2,2–4,0.5,Bayern Munich,30000.0,Volkswagen Arena,Harm Osmers,Match Report,NaN,/en/matches/29fe863b/Wolfsburg-Bayern-Munich-F...,Bundesliga
171,20.0,Fri,2023-02-10,20:30,Schalke 04,1.3,0–0,1.3,Wolfsburg,NaN,Veltins-Arena,Benjamin Brand,Match Report,NaN,/en/matches/ee7ae28f/Schalke-04-Wolfsburg-Febr...,Bundesliga
172,20.0,Sat,2023-02-11,15:30,Bayern Munich,3.7,3–0,0.3,Bochum,75000.0,Allianz Arena,Matthias Jöllenbeck,Match Report,NaN,/en/matches/5965a1a5/Bayern-Munich-Bochum-Febr...,Bundesliga

### Fixing Broken Data

In [ ]:
import bs4
import requests
import time

In [ ]:
def get_html_document(url):
  # request for HTML document of given url
  response = requests.get(url)
  # response will be provided in JSON format
  return response.text

In [ ]:
def scrape_team(team_id, team_name):
  team_url = f'https://fbref.com/en/squads/{team_id}/{team_name}-Stats'
  html_doc = get_html_document(team_url)
  soup = bs4.BeautifulSoup(html_doc, 'html.parser')
  return soup

In [ ]:
def clean_team_stats_table(raw_table):
  # remove the multi-index
  # ex: column name ('Playing Time', 'MP') becomes ('Playing Time - MP')
  for col in raw_table.columns:
    if 'unnamed' in col[0].lower():
      continue
    new_colname = col[0] + ' - ' + col[1]

    # column reassignment is used instead of rename because rename changes 
    # all the columns with the desired name
    raw_table[('', new_colname)] = raw_table[col]
    raw_table.drop(columns=[col], inplace=True, axis=1)

  # change the column structure to make it just 1 level
  raw_table = raw_table.droplevel(level=0, axis=1)

  # drop unneeded columns & rows
  raw_table = raw_table.drop(["Matches"], axis=1)
  raw_table = raw_table[
      (raw_table["Player"] != "Squad Total") &
      (raw_table["Player"] != "Opponent Total")
  ]

  # Change NaN values to 0
  raw_table = raw_table.fillna(0)
  
  # Convert string values to numeric
  for col in raw_table.columns:
    raw_table[col] = pd.to_numeric(
        raw_table[col], 
        errors='ignore',
    )
  
  return raw_table

In [ ]:
def create_player_columns(team_id="822bd0ba", team_name="Liverpool"):
    # get html doc of the team
    team_soup = scrape_team(team_id, team_name)

    # get html table of playing time
    stats_list = ["standard",]
    stats_table_list = []

    for stats in stats_list:
        # get individual table of each statistic category
        table_soup = team_soup.find('table', attrs={'id': f"stats_{stats}_9"})
        table_raw = pd.read_html(str(table_soup))[0]
        table_clean = clean_team_stats_table(table_raw)

        # rename the columns to mark from where the columns was obtained
        table_clean = table_clean.set_index("Player")
        for col in table_clean.columns:
            table_clean.rename(columns={col: f"{stats} - {col}"}, inplace=True)
        table_clean = table_clean.reset_index("Player")

        stats_table_list.append(table_clean)

    df_players = stats_table_list[0]
    df_players_one_row = df_players.set_index("Player")
    df_players_one_row.columns = pd.MultiIndex.from_product([[team_name], df_players_one_row.columns])
    # pakai column name Club -- Player - Statistics
    df_players_one_row = df_players_one_row.unstack().to_frame().T
    df_players_one_row = df_players_one_row.swaplevel(1, axis=1).sort_values("Player", axis=1)
    df_players_one_row.columns.names = ["Club", "Player", "Statistic"]

    return df_players_one_row

In [ ]:
# ## Code to fix broken scrapped data
# ## the level 0 of the column all has the same values
# ## which is Fulham, since I tried to hard-coded it for testing purpose
# ## but then forgot to change it to variable
# ## so basically even though the names and statistics were correct, 
# ## the club names weren't

# for idx, row in df_recorded_matches.iterrows():
#     home = TEAM_DISPLAY[row["Home"]]
#     away = TEAM_DISPLAY[row["Away"]]
#     date = row["Date"]
#     print("File:", f"{SAVE_DIR}/{date}_{home}-vs-{away}")

#     # open csv file
#     df_csv = pd.read_csv(f"{SAVE_DIR}/{date}_{home}-vs-{away}.csv", index_col=0, header=[0, 1, 2])
#     col_names = df_csv.columns.names

#     # scrap home team
#     home_players = create_player_columns(TEAM_CODE[home], home)
#     # get list of players of the home team
#     home_players = list(set([col[1] for col in home_players.columns.tolist()]))

#     # sleep for 3 seconds to delay scraping just not too spam the requests to fbref
#     time.sleep(3)

#     # # scrap away team
#     away_players = create_player_columns(TEAM_CODE[away], away)
#     # get list of players of the away team
#     away_players = list(set([col[1] for col in away_players.columns.tolist()]))

#     new_cols = [[home, col[1], col[2]] if col[1] in home_players else [away, col[1], col[2]] for col in df_csv.columns]
#     new_cols = pd.MultiIndex.from_arrays(np.array(new_cols).T)

#     # assign new columns and their names
#     df_csv.columns = new_cols
#     df_csv.columns.names = col_names

#     # save to csv with different name just in case
#     df_csv.to_csv(f"{SAVE_DIR}/{date}_{home}-vs-{away}.csv")

### Transforming Data

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

In [ ]:
position_mlb = MultiLabelBinarizer(classes=POSITION_CHOICES)

In [ ]:
register_features = [
    # pre-match player information/stats
    'keeper - Performance - Save%',
    'keeper - Performance - CS%',
    'keeper_adv - Expected - PSxG/SoT',
    'keeper_adv - Expected - /90',
    'shooting - Standard - SoT%',
    'shooting - Standard - SoT/90',
    'shooting - Standard - G/SoT',
    'shooting - Expected - G-xG',
    'passing - xAG',
    'passing - xA',
    'passing - KP',
    'gca - SCA - SCA90',
    'gca - GCA - GCA90',
    'defense - Tkl+Int',
    'defense - Clr',
    'defense - Blocks - Blocks',
    'playing_time - Team Success - PPM',
    'playing_time - Team Success (xG) - On-Off',
    'misc - Performance - Recov',
    'misc - Aerial Duels - Won%',
    # post-match player information/stats
    "Pos",
]

In [ ]:
def get_data_for_ml(
    df_recorded_matches: pd.DataFrame, 
    features: list, 
    starter_only: bool = True, 
    ignore_new_players: bool = True,
    df_for_ml: pd.DataFrame or None = None,
    save_dir = None
) -> np.ndarray:
    if df_for_ml is None:
        df_for_ml = pd.DataFrame()
    check_cols = features

    for idx, row in df_recorded_matches.reset_index(drop=True).iterrows():
        
        ###Iterate and combine csv and json files to feed into the ML model
        home = TEAM_DISPLAY[row["Home"]]
        away = TEAM_DISPLAY[row["Away"]]
        date = row["Date"]
        print("Processing:", f"{date}_{home}-vs-{away}")

        try:
            # open csv file
            df_csv = pd.read_csv(f"{save_dir}/{date}_{home}-vs-{away}.csv", index_col=0, header=[0, 1, 2])
            
            # open json file
            json_file = json.load(open(f"{save_dir}/{date}_{home}-vs-{away}.json"))
            # iterate over home team
            home_starters = []
            for player, attributes in json_file[home].items():
                if starter_only:
                    if "(Sub)" in player:
                        continue
                df_csv[home, player, "Pos"] = attributes["Pos"]
                df_csv[home, player, "Age"] = attributes["Age"]
                df_csv[home, player, "Min"] = attributes["Min"]
                home_starters.append(player)
                
            # iterate over away team
            away_starters = []
            for player, attributes in json_file[away].items():
                if starter_only:
                    if "(Sub)" in player:
                        continue
                df_csv[away, player, "Pos"] = attributes["Pos"]
                df_csv[away, player, "Age"] = attributes["Age"]
                df_csv[away, player, "Min"] = attributes["Min"]
                away_starters.append(player)

            # concate column-wise
            df_per_row = df_csv.copy()
            assert len(home_starters) == len(away_starters) == 11
            df_home = df_per_row.loc[:, pd.IndexSlice[home, home_starters, features]].copy()
            df_away = df_per_row.loc[:, pd.IndexSlice[away, away_starters, features]].copy()
            
            _home_starters_recorded = df_home.columns.get_level_values("Player").unique()
            _away_starters_recorded = df_away.columns.get_level_values("Player").unique()
            if ignore_new_players is False:
                # checking team starters that have been fetched from the dataframe
                # if the dataframe of a team contains less than 11 players
                # then that means there is a player that just debuted in that match
                ## for each team check remaining players needed, then
                ##      create numpy array based on the dimension
                ##      create the df along the columns
                ##      concat column-wise with the home/away dataframe
                assert len(_home_starters_recorded) == len(_away_starters_recorded) == 11
            
            if len(_home_starters_recorded) != 11 or len(_away_starters_recorded) != 11:
                # ignore match whose team that has less than 11 players recorded on the match
                print("    Match Ignored since No 11 vs 11")
                continue
            
            # rename player columns from their original names to Player 1, Player 2, etc.
            numbered_player_cols = ["Player_"+f"{i}".zfill(2) for i in range(1, 11+1)]
            # for home team
            real_player_cols = df_home.columns.get_level_values(level="Player")
            real_player_cols_unique = real_player_cols.unique().tolist()
            cols_mapping = {key: value for key, value in zip(real_player_cols_unique, numbered_player_cols)}
            home_level_1 = ["Home"] * 11 * len(features)
            home_level_2 = [cols_mapping[player_name] for player_name in real_player_cols.tolist()]
            home_level_3 = df_home.columns.get_level_values(level=2)
            if len(home_level_1) != len(home_level_2) or \
                len(home_level_1) != len(home_level_3) or \
                len(home_level_2) != len(home_level_3):
                print("    Inconsistent array length construction. Match ignored")
                continue
            new_cols_home = pd.MultiIndex.from_arrays([
                home_level_1,
                home_level_2,
                home_level_3
            ])
            df_home.columns = new_cols_home

            # for away team
            real_player_cols = df_away.columns.get_level_values(level="Player")
            real_player_cols_unique = real_player_cols.unique().tolist()
            cols_mapping = {key: value for key, value in zip(real_player_cols_unique, numbered_player_cols)}
            away_level_1 = ["Away"] * 11 * len(features)
            away_level_2 = [cols_mapping[player_name] for player_name in real_player_cols.tolist()]
            away_level_3 = df_away.columns.get_level_values(level=2)
            if len(away_level_1) != len(away_level_2) or \
                len(away_level_1) != len(away_level_3) or \
                len(away_level_2) != len(away_level_3):
                print("    Inconsistent array length construction. Match ignored")
                continue
            new_cols_away = pd.MultiIndex.from_arrays([
                away_level_1,
                away_level_2,
                away_level_3
            ])
            df_away.columns = new_cols_away    

            # concat column-wise home and away df
            df_per_row = pd.concat([df_home, df_away], axis=1)

            # checking inconsistent columns
            cols = df_per_row.columns.get_level_values(level="Statistic").unique()
            diff_cols = [col for col in cols if col not in check_cols]
            if len(cols) != len(check_cols) and len(check_cols) == 0:
                check_cols = cols
            assert len(diff_cols) == 0

            # get the score
            home_score = int(row["Score"].split("–")[0])
            away_score = int(row["Score"].split("–")[1])
            scores = [[home_score, away_score]]
            columns_Y = pd.MultiIndex.from_arrays([
                ["Home", "Away"],
                ["----", "----"],
                ["Score", "Score"]
            ])
            scores = pd.DataFrame(
                scores,
                columns=columns_Y
            )
            df_per_row = pd.concat([df_per_row, scores], axis=1)
            df_per_row = df_per_row.fillna(0)
            ## save transformed csv
            # df_per_row.to_csv(f"{TRANSFORM_DIR}/{date}_{home}-vs-{away}.csv")
            
            # concate row-wise
            df_for_ml = pd.concat([df_for_ml, df_per_row], axis=0)
        except:
            print("    Failed. Somehow.")
            continue

    df_for_ml.columns.names = ["Club", "Player", "Statistic"]
    return df_for_ml.reset_index(drop=True)

In [ ]:
LEAGUES = [
    "Premier-League",
    "Serie-A", 
    "La-Liga", 
    "Ligue-1", 
    "Bundesliga"
]
INDEX_START_SCRAPPING = [
    197, 
    200,
    191,
    210,
    163
]

In [ ]:
for idx, league in enumerate(LEAGUES):
    print("Processing League:", league)
    TABLE_REF_PATH = os.path.join(DATA_DIR, f"raw/{LEAGUES[idx]}/table_ref.csv")
    save_dir = os.path.join(DATA_DIR, f"raw/{LEAGUES[idx]}/2022-2023_Matches")
    
    table_ref = pd.read_csv(TABLE_REF_PATH, index_col=0)
    cond = table_ref["Score"].notnull()
    cond2 = table_ref.index >= INDEX_START_SCRAPPING[idx]
    df_recorded_matches = table_ref.loc[cond & cond2, :]

    if idx == 0:
        dataset = get_data_for_ml(df_recorded_matches, features=register_features, save_dir=save_dir)
    else:
        dataset = get_data_for_ml(df_recorded_matches, features=register_features, save_dir=save_dir, df_for_ml=dataset)
    print("\n")

Processing League: Premier-League
Processing: 2023-01-22_Arsenal-vs-Manchester-United
Processing: 2023-01-23_Fulham-vs-Tottenham-Hotspur
    Failed. Somehow.
Processing: 2023-02-03_Chelsea-vs-Fulham
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Everton-vs-Arsenal
Processing: 2023-02-04_Aston-Villa-vs-Leicester-City
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Wolverhampton-Wanderers-vs-Liverpool
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Manchester-United-vs-Crystal-Palace
    Failed. Somehow.
Processing: 2023-02-04_Brighton-and-Hove-Albion-vs-Bournemouth
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Brentford-vs-Southampton
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Newcastle-United-vs-West-Ham-United
Processing: 2023-02-05_Nottingham-Forest-vs-Leeds-United
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Tottenham-Hotspur-vs-Manchester-City
    Failed. Somehow.
Processing: 2023-02-08_Manchester-United-vs-Leeds-United
Processing: 2023-02-11_West-Ham-United-vs-Chelsea
Processing: 2023-02-11_Leicester-City-vs-Tottenham-Hotspur
Processing: 2023-02-11_Crystal-Palace-vs-Brighton-and-Hove-Albion
Processing: 2023-02-11_Arsenal-vs-Brentford
Processing: 2023-02-11_Southampton-vs-Wolverhampton-Wanderers
    Failed. Somehow.
Processing: 2023-02-11_Fulham-vs-Nottingham-Forest
Processing: 2023-02-11_Bournemouth-vs-Newcastle-United
Processing: 2023-02-12_Leeds-United-vs-Manchester-United
Processing: 2023-02-12_Manchester-City-vs-Aston-Villa
Processing: 2023-02-13_Liverpool-vs-Everton
Processing: 2023-02-15_Arsenal-vs-Manchester-City
Processing: 2023-02-18_Aston-Villa-vs-Arsenal
Processing: 2023-02-18_Brighton-and-Hove-Albion-vs-Fulham
Processing: 2023-02-18_Nottingham-Forest-vs-Manchester-City
Processing: 2023-02-18_Chelsea-vs-Southampton
Processing: 2023-02-18_Everton-vs-Leeds-United
Processing: 2023-02-18_Wolverhampton-Wanderers-vs-Bournemouth
Processing: 2023-02-18_Brentford-vs-Crystal-Palace
Processing: 2023-02-18_Newcastle-United-vs-Liverpool
Processing: 2023-02-19_Manchester-United-vs-Leicester-City
Processing: 2023-02-19_Tottenham-Hotspur-vs-West-Ham-United
Processing: 2023-02-24_Fulham-vs-Wolverhampton-Wanderers
Processing: 2023-02-25_Leicester-City-vs-Arsenal
Processing: 2023-02-25_Everton-vs-Aston-Villa
Processing: 2023-02-25_West-Ham-United-vs-Nottingham-Forest
Processing: 2023-02-25_Leeds-United-vs-Southampton
Processing: 2023-02-25_Bournemouth-vs-Manchester-City
Processing: 2023-02-25_Crystal-Palace-vs-Liverpool
Processing: 2023-02-26_Tottenham-Hotspur-vs-Chelsea
Processing: 2023-03-01_Arsenal-vs-Everton
Processing: 2023-03-01_Liverpool-vs-Wolverhampton-Wanderers
Processing: 2023-03-04_Manchester-City-vs-Newcastle-United
Processing: 2023-03-04_Arsenal-vs-Bournemouth
Processing: 2023-03-04_Aston-Villa-vs-Crystal-Palace
    Failed. Somehow.
Processing: 2023-03-04_Chelsea-vs-Leeds-United
Processing: 2023-03-04_Brighton-and-Hove-Albion-vs-West-Ham-United
Processing: 2023-03-04_Wolverhampton-Wanderers-vs-Tottenham-Hotspur
Processing: 2023-03-04_Southampton-vs-Leicester-City
Processing: 2023-03-05_Nottingham-Forest-vs-Everton
Processing: 2023-03-05_Liverpool-vs-Manchester-United
Processing: 2023-03-06_Brentford-vs-Fulham
Processing: 2023-03-11_Bournemouth-vs-Liverpool
Processing: 2023-03-11_Leeds-United-vs-Brighton-and-Hove-Albion
Processing: 2023-03-11_Everton-vs-Brentford
Processing: 2023-03-11_Leicester-City-vs-Chelsea
    Failed. Somehow.
Processing: 2023-03-11_Tottenham-Hotspur-vs-Nottingham-Forest
Processing: 2023-03-11_Crystal-Palace-vs-Manchester-City
Processing: 2023-03-12_Manchester-United-vs-Southampton
Processing: 2023-03-12_Fulham-vs-Arsenal
Processing: 2023-03-12_West-Ham-United-vs-Aston-Villa
Processing: 2023-03-12_Newcastle-United-vs-Wolverhampton-Wanderers
Processing: 2023-03-15_Southampton-vs-Brentford
Processing: 2023-03-15_Brighton-and-Hove-Albion-vs-Crystal-Palace
Processing: 2023-03-17_Nottingham-Forest-vs-Newcastle-United
Processing: 2023-03-18_Wolverhampton-Wanderers-vs-Leeds-United
    Failed. Somehow.
Processing: 2023-03-18_Brentford-vs-Leicester-City
Processing: 2023-03-18_Aston-Villa-vs-Bournemouth
Processing: 2023-03-18_Southampton-vs-Tottenham-Hotspur
Processing: 2023-03-18_Chelsea-vs-Everton
Processing: 2023-03-19_Arsenal-vs-Crystal-Palace
Processing: 2023-04-01_Manchester-City-vs-Liverpool
    Failed. Somehow.
Processing: 2023-04-01_Arsenal-vs-Leeds-United
Processing: 2023-04-01_Nottingham-Forest-vs-Wolverhampton-Wanderers
Processing: 2023-04-01_Brighton-and-Hove-Albion-vs-Brentford
Processing: 2023-04-01_Crystal-Palace-vs-Leicester-City
Processing: 2023-04-01_Bournemouth-vs-Fulham
Processing: 2023-04-01_Chelsea-vs-Aston-Villa
Processing: 2023-04-02_West-Ham-United-vs-Southampton
Processing: 2023-04-02_Newcastle-United-vs-Manchester-United
Processing: 2023-04-03_Everton-vs-Tottenham-Hotspur
    Failed. Somehow.
Processing: 2023-04-04_Leeds-United-vs-Nottingham-Forest
Processing: 2023-04-04_Bournemouth-vs-Brighton-and-Hove-Albion
Processing: 2023-04-04_Leicester-City-vs-Aston-Villa
    Failed. Somehow.
Processing: 2023-04-04_Chelsea-vs-Liverpool
Processing: 2023-04-05_West-Ham-United-vs-Newcastle-United
Processing: 2023-04-05_Manchester-United-vs-Brentford
Processing: 2023-04-08_Manchester-United-vs-Everton
Processing: 2023-04-08_Fulham-vs-West-Ham-United
Processing: 2023-04-08_Aston-Villa-vs-Nottingham-Forest
Processing: 2023-04-08_Leicester-City-vs-Bournemouth
Processing: 2023-04-08_Brentford-vs-Newcastle-United
Processing: 2023-04-08_Wolverhampton-Wanderers-vs-Chelsea
Processing: 2023-04-08_Tottenham-Hotspur-vs-Brighton-and-Hove-Albion
Processing: 2023-04-08_Southampton-vs-Manchester-City
Processing: 2023-04-09_Leeds-United-vs-Crystal-Palace
Processing: 2023-04-09_Liverpool-vs-Arsenal


Processing League: Serie-A
Processing: 2023-02-04_Cremonese-vs-Lecce
Processing: 2023-02-04_Roma-vs-Empoli
Processing: 2023-02-04_Sassuolo-vs-Atalanta
    Failed. Somehow.
Processing: 2023-02-05_Spezia-vs-Napoli
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Torino-vs-Udinese
Processing: 2023-02-05_Fiorentina-vs-Bologna
    Failed. Somehow.
Processing: 2023-02-05_Internazionale-vs-Milan
    Failed. Somehow.
Processing: 2023-02-06_Hellas-Verona-vs-Lazio
Processing: 2023-02-06_Monza-vs-Sampdoria
    Inconsistent array length construction. Match ignored
Processing: 2023-02-07_Salernitana-vs-Juventus
Processing: 2023-02-10_Milan-vs-Torino
Processing: 2023-02-11_Empoli-vs-Spezia
    Failed. Somehow.
Processing: 2023-02-11_Lecce-vs-Roma
Processing: 2023-02-11_Lazio-vs-Atalanta
Processing: 2023-02-12_Udinese-vs-Sassuolo
Processing: 2023-02-12_Bologna-vs-Monza
Processing: 2023-02-12_Juventus-vs-Fiorentina
Processing: 2023-02-12_Napoli-vs-Cremonese
Processing: 2023-02-13_Hellas-Verona-vs-Salernitana
Processing: 2023-02-13_Sampdoria-vs-Internazionale
Processing: 2023-02-17_Sassuolo-vs-Napoli
Processing: 2023-02-18_Sampdoria-vs-Bologna
Processing: 2023-02-18_Monza-vs-Milan
Processing: 2023-02-18_Internazionale-vs-Udinese
Processing: 2023-02-19_Atalanta-vs-Lecce
Processing: 2023-02-19_Salernitana-vs-Lazio
    Failed. Somehow.
Processing: 2023-02-19_Fiorentina-vs-Empoli
Processing: 2023-02-19_Spezia-vs-Juventus
Processing: 2023-02-19_Roma-vs-Hellas-Verona
Processing: 2023-02-20_Torino-vs-Cremonese
Processing: 2023-02-25_Empoli-vs-Napoli
    Failed. Somehow.
Processing: 2023-02-25_Lecce-vs-Sassuolo
Processing: 2023-02-26_Bologna-vs-Internazionale
Processing: 2023-02-26_Salernitana-vs-Monza
Processing: 2023-02-26_Udinese-vs-Spezia
Processing: 2023-02-26_Milan-vs-Atalanta
Processing: 2023-02-27_Hellas-Verona-vs-Fiorentina
Processing: 2023-02-27_Lazio-vs-Sampdoria
Processing: 2023-02-28_Cremonese-vs-Roma
Processing: 2023-02-28_Juventus-vs-Torino
Processing: 2023-03-03_Napoli-vs-Lazio
Processing: 2023-03-04_Monza-vs-Empoli
Processing: 2023-03-04_Atalanta-vs-Udinese
Processing: 2023-03-04_Fiorentina-vs-Milan
Processing: 2023-03-05_Spezia-vs-Hellas-Verona
Processing: 2023-03-05_Sampdoria-vs-Salernitana
Processing: 2023-03-05_Internazionale-vs-Lecce
Processing: 2023-03-05_Roma-vs-Juventus
Processing: 2023-03-06_Sassuolo-vs-Cremonese
Processing: 2023-03-06_Torino-vs-Bologna
Processing: 2023-03-10_Spezia-vs-Internazionale
Processing: 2023-03-11_Empoli-vs-Udinese
Processing: 2023-03-11_Napoli-vs-Atalanta
Processing: 2023-03-11_Bologna-vs-Lazio
Processing: 2023-03-12_Lecce-vs-Torino
Processing: 2023-03-12_Cremonese-vs-Fiorentina
Processing: 2023-03-12_Hellas-Verona-vs-Monza
Processing: 2023-03-12_Roma-vs-Sassuolo
    Failed. Somehow.
Processing: 2023-03-12_Juventus-vs-Sampdoria
Processing: 2023-03-13_Milan-vs-Salernitana
Processing: 2023-03-17_Sassuolo-vs-Spezia
Processing: 2023-03-17_Atalanta-vs-Empoli
Processing: 2023-03-18_Monza-vs-Cremonese
Processing: 2023-03-18_Salernitana-vs-Bologna
Processing: 2023-03-18_Udinese-vs-Milan
Processing: 2023-03-19_Sampdoria-vs-Hellas-Verona
Processing: 2023-03-19_Fiorentina-vs-Lecce
Processing: 2023-03-19_Torino-vs-Napoli
Processing: 2023-03-19_Lazio-vs-Roma
    Failed. Somehow.
Processing: 2023-03-19_Internazionale-vs-Juventus
    Failed. Somehow.
Processing: 2023-04-01_Cremonese-vs-Atalanta
Processing: 2023-04-01_Internazionale-vs-Fiorentina
Processing: 2023-04-01_Juventus-vs-Hellas-Verona
Processing: 2023-04-02_Bologna-vs-Udinese
Processing: 2023-04-02_Spezia-vs-Salernitana
Processing: 2023-04-02_Monza-vs-Lazio
Processing: 2023-04-02_Roma-vs-Sampdoria
    Failed. Somehow.
Processing: 2023-04-02_Napoli-vs-Milan
Processing: 2023-04-03_Empoli-vs-Lecce
Processing: 2023-04-03_Sassuolo-vs-Torino
Processing: 2023-04-07_Salernitana-vs-Internazionale
Processing: 2023-04-07_Lecce-vs-Napoli
Processing: 2023-04-07_Milan-vs-Empoli
Processing: 2023-04-08_Udinese-vs-Monza
Processing: 2023-04-08_Fiorentina-vs-Spezia
Processing: 2023-04-08_Atalanta-vs-Bologna
Processing: 2023-04-08_Sampdoria-vs-Cremonese
Processing: 2023-04-08_Hellas-Verona-vs-Sassuolo
Processing: 2023-04-08_Torino-vs-Roma
Processing: 2023-04-08_Lazio-vs-Juventus


Processing League: La-Liga
Processing: 2023-02-04_Espanyol-vs-Osasuna
    Failed. Somehow.
Processing: 2023-02-04_Elche-vs-Villarreal
Processing: 2023-02-04_Atletico-Madrid-vs-Getafe
Processing: 2023-02-04_Real-Betis-vs-Celta-Vigo
    Failed. Somehow.
Processing: 2023-02-05_Mallorca-vs-Real-Madrid
Processing: 2023-02-05_Girona-vs-Valencia
Processing: 2023-02-05_Real-Sociedad-vs-Valladolid
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Barcelona-vs-Sevilla
    Inconsistent array length construction. Match ignored
Processing: 2023-02-06_Rayo-Vallecano-vs-Almeria
Processing: 2023-02-10_Cadiz-vs-Girona
Processing: 2023-02-11_Almeria-vs-Real-Betis
Processing: 2023-02-11_Sevilla-vs-Mallorca
Processing: 2023-02-11_Valencia-vs-Athletic-Club
Processing: 2023-02-12_Getafe-vs-Rayo-Vallecano
    Failed. Somehow.
Processing: 2023-02-12_Celta-Vigo-vs-Atletico-Madrid
    Failed. Somehow.
Processing: 2023-02-12_Valladolid-vs-Osasuna
Processing: 2023-02-12_Villarreal-vs-Barcelona
Processing: 2023-02-13_Espanyol-vs-Real-Sociedad
    Failed. Somehow.
Processing: 2023-02-15_Real-Madrid-vs-Elche
Processing: 2023-02-17_Girona-vs-Almeria
Processing: 2023-02-18_Real-Sociedad-vs-Celta-Vigo
Processing: 2023-02-18_Real-Betis-vs-Valladolid
Processing: 2023-02-18_Mallorca-vs-Villarreal
    Failed. Somehow.
Processing: 2023-02-18_Osasuna-vs-Real-Madrid
Processing: 2023-02-19_Elche-vs-Espanyol
    Failed. Somehow.
Processing: 2023-02-19_Rayo-Vallecano-vs-Sevilla
Processing: 2023-02-19_Atletico-Madrid-vs-Athletic-Club
Processing: 2023-02-19_Barcelona-vs-Cadiz
Processing: 2023-02-20_Getafe-vs-Valencia
Processing: 2023-02-24_Elche-vs-Real-Betis
    Failed. Somehow.
Processing: 2023-02-25_Espanyol-vs-Mallorca
Processing: 2023-02-25_Cadiz-vs-Rayo-Vallecano
    Failed. Somehow.
Processing: 2023-02-25_Real-Madrid-vs-Atletico-Madrid
    Failed. Somehow.
Processing: 2023-02-25_Valencia-vs-Real-Sociedad
Processing: 2023-02-26_Athletic-Club-vs-Girona
Processing: 2023-02-26_Celta-Vigo-vs-Valladolid
Processing: 2023-02-26_Almeria-vs-Barcelona
Processing: 2023-02-26_Sevilla-vs-Osasuna
Processing: 2023-02-27_Villarreal-vs-Getafe
Processing: 2023-03-03_Real-Sociedad-vs-Cadiz
Processing: 2023-03-04_Getafe-vs-Girona
Processing: 2023-03-04_Almeria-vs-Villarreal
Processing: 2023-03-04_Mallorca-vs-Elche
Processing: 2023-03-04_Atletico-Madrid-vs-Sevilla
    Failed. Somehow.
Processing: 2023-03-05_Valladolid-vs-Espanyol
Processing: 2023-03-05_Barcelona-vs-Valencia
    Failed. Somehow.
Processing: 2023-03-05_Rayo-Vallecano-vs-Athletic-Club
    Failed. Somehow.
Processing: 2023-03-05_Real-Betis-vs-Real-Madrid
Processing: 2023-03-06_Osasuna-vs-Celta-Vigo
Processing: 2023-03-10_Cadiz-vs-Getafe
    Failed. Somehow.
Processing: 2023-03-11_Real-Madrid-vs-Espanyol
Processing: 2023-03-11_Elche-vs-Valladolid
    Failed. Somehow.
Processing: 2023-03-11_Celta-Vigo-vs-Rayo-Vallecano
Processing: 2023-03-11_Valencia-vs-Osasuna
Processing: 2023-03-12_Mallorca-vs-Real-Sociedad
    Failed. Somehow.
Processing: 2023-03-12_Sevilla-vs-Almeria
Processing: 2023-03-12_Villarreal-vs-Real-Betis
Processing: 2023-03-12_Athletic-Club-vs-Barcelona
Processing: 2023-03-13_Girona-vs-Atletico-Madrid
Processing: 2023-03-17_Valladolid-vs-Athletic-Club
Processing: 2023-03-18_Almeria-vs-Cadiz
Processing: 2023-03-18_Rayo-Vallecano-vs-Girona
Processing: 2023-03-18_Espanyol-vs-Celta-Vigo
Processing: 2023-03-18_Atletico-Madrid-vs-Valencia
Processing: 2023-03-19_Real-Betis-vs-Mallorca
Processing: 2023-03-19_Osasuna-vs-Villarreal
Processing: 2023-03-19_Real-Sociedad-vs-Elche
Processing: 2023-03-19_Getafe-vs-Sevilla
Processing: 2023-03-19_Barcelona-vs-Real-Madrid
    Failed. Somehow.
Processing: 2023-03-31_Mallorca-vs-Osasuna
    Failed. Somehow.
Processing: 2023-04-01_Girona-vs-Espanyol
    Failed. Somehow.
Processing: 2023-04-01_Athletic-Club-vs-Getafe
Processing: 2023-04-01_Cadiz-vs-Sevilla
Processing: 2023-04-01_Elche-vs-Barcelona
Processing: 2023-04-02_Celta-Vigo-vs-Almeria
Processing: 2023-04-02_Real-Madrid-vs-Valladolid
Processing: 2023-04-02_Villarreal-vs-Real-Sociedad
Processing: 2023-04-02_Atletico-Madrid-vs-Real-Betis
Processing: 2023-04-03_Valencia-vs-Rayo-Vallecano
Processing: 2023-04-07_Sevilla-vs-Celta-Vigo
    Failed. Somehow.
Processing: 2023-04-08_Osasuna-vs-Elche
Processing: 2023-04-08_Espanyol-vs-Athletic-Club
Processing: 2023-04-08_Real-Sociedad-vs-Getafe
Processing: 2023-04-08_Real-Madrid-vs-Villarreal
Processing: 2023-04-09_Valladolid-vs-Mallorca
Processing: 2023-04-09_Real-Betis-vs-Cadiz
    Failed. Somehow.
Processing: 2023-04-09_Almeria-vs-Valencia
Processing: 2023-04-09_Rayo-Vallecano-vs-Atletico-Madrid
    Failed. Somehow.
Processing: 2023-04-10_Barcelona-vs-Girona


Processing League: Ligue-1
Processing: 2023-02-04_Paris-Saint-Germain-vs-Toulouse
Processing: 2023-02-04_Troyes-vs-Lyon
Processing: 2023-02-04_Rennes-vs-Lille
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Clermont-Foot-vs-Monaco
Processing: 2023-02-05_Strasbourg-vs-Montpellier
    Failed. Somehow.
Processing: 2023-02-05_Ajaccio-vs-Nantes
    Failed. Somehow.
Processing: 2023-02-05_Auxerre-vs-Reims
Processing: 2023-02-05_Lorient-vs-Angers
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Brest-vs-Lens
Processing: 2023-02-05_Marseille-vs-Nice
    Inconsistent array length construction. Match ignored
Processing: 2023-02-10_Nice-vs-Ajaccio
Processing: 2023-02-11_Monaco-vs-Paris-Saint-Germain
Processing: 2023-02-11_Clermont-Foot-vs-Marseille
Processing: 2023-02-12_Toulouse-vs-Rennes
Processing: 2023-02-12_Angers-vs-Auxerre
Processing: 2023-02-12_Lille-vs-Strasbourg
Processing: 2023-02-12_Montpellier-vs-Brest
Processing: 2023-02-12_Reims-vs-Troyes
Processing: 2023-02-12_Nantes-vs-Lorient
Processing: 2023-02-12_Lyon-vs-Lens
Processing: 2023-02-17_Auxerre-vs-Lyon
Processing: 2023-02-18_Nice-vs-Reims
Processing: 2023-02-18_Strasbourg-vs-Angers
Processing: 2023-02-19_Paris-Saint-Germain-vs-Lille
Processing: 2023-02-19_Troyes-vs-Montpellier
    Failed. Somehow.
Processing: 2023-02-19_Lorient-vs-Ajaccio
Processing: 2023-02-19_Brest-vs-Monaco
Processing: 2023-02-19_Rennes-vs-Clermont-Foot
Processing: 2023-02-19_Lens-vs-Nantes
Processing: 2023-02-19_Toulouse-vs-Marseille
Processing: 2023-02-24_Lille-vs-Brest
Processing: 2023-02-25_Angers-vs-Lyon
Processing: 2023-02-25_Montpellier-vs-Lens
Processing: 2023-02-26_Lorient-vs-Auxerre
Processing: 2023-02-26_Clermont-Foot-vs-Strasbourg
Processing: 2023-02-26_Ajaccio-vs-Troyes
    Failed. Somehow.
Processing: 2023-02-26_Reims-vs-Toulouse
Processing: 2023-02-26_Nantes-vs-Rennes
Processing: 2023-02-26_Monaco-vs-Nice
    Inconsistent array length construction. Match ignored
Processing: 2023-02-26_Marseille-vs-Paris-Saint-Germain
Processing: 2023-03-03_Nice-vs-Auxerre
Processing: 2023-03-04_Lens-vs-Lille
Processing: 2023-03-04_Paris-Saint-Germain-vs-Nantes
Processing: 2023-03-05_Troyes-vs-Monaco
Processing: 2023-03-05_Montpellier-vs-Angers
    Failed. Somehow.
Processing: 2023-03-05_Toulouse-vs-Clermont-Foot
Processing: 2023-03-05_Strasbourg-vs-Brest
Processing: 2023-03-05_Reims-vs-Ajaccio
Processing: 2023-03-05_Lyon-vs-Lorient
Processing: 2023-03-05_Rennes-vs-Marseille
Processing: 2023-03-10_Lille-vs-Lyon
Processing: 2023-03-11_Auxerre-vs-Rennes
Processing: 2023-03-11_Brest-vs-Paris-Saint-Germain
Processing: 2023-03-12_Clermont-Foot-vs-Lens
Processing: 2023-03-12_Lorient-vs-Troyes
Processing: 2023-03-12_Ajaccio-vs-Montpellier
Processing: 2023-03-12_Nantes-vs-Nice
Processing: 2023-03-12_Angers-vs-Toulouse
Processing: 2023-03-12_Monaco-vs-Reims
Processing: 2023-03-12_Marseille-vs-Strasbourg
    Failed. Somehow.
Processing: 2023-03-17_Lyon-vs-Nantes
Processing: 2023-03-18_Toulouse-vs-Lille
Processing: 2023-03-18_Lens-vs-Angers
Processing: 2023-03-19_Ajaccio-vs-Monaco
    Failed. Somehow.
Processing: 2023-03-19_Nice-vs-Lorient
    Failed. Somehow.
Processing: 2023-03-19_Strasbourg-vs-Auxerre
Processing: 2023-03-19_Troyes-vs-Brest
Processing: 2023-03-19_Montpellier-vs-Clermont-Foot
    Failed. Somehow.
Processing: 2023-03-19_Paris-Saint-Germain-vs-Rennes
Processing: 2023-03-19_Reims-vs-Marseille
Processing: 2023-03-31_Marseille-vs-Montpellier
Processing: 2023-04-01_Auxerre-vs-Troyes
Processing: 2023-04-01_Rennes-vs-Lens
Processing: 2023-04-02_Lille-vs-Lorient
    Failed. Somehow.
Processing: 2023-04-02_Brest-vs-Toulouse
    Failed. Somehow.
Processing: 2023-04-02_Angers-vs-Nice
    Inconsistent array length construction. Match ignored
Processing: 2023-04-02_Clermont-Foot-vs-Ajaccio
Processing: 2023-04-02_Nantes-vs-Reims
Processing: 2023-04-02_Monaco-vs-Strasbourg
    Failed. Somehow.
Processing: 2023-04-02_Paris-Saint-Germain-vs-Lyon
Processing: 2023-04-07_Lens-vs-Strasbourg
    Failed. Somehow.
Processing: 2023-04-08_Angers-vs-Lille
Processing: 2023-04-08_Nice-vs-Paris-Saint-Germain
Processing: 2023-04-09_Lyon-vs-Rennes
Processing: 2023-04-09_Montpellier-vs-Toulouse
Processing: 2023-04-09_Ajaccio-vs-Auxerre
Processing: 2023-04-09_Reims-vs-Brest
Processing: 2023-04-09_Troyes-vs-Clermont-Foot
Processing: 2023-04-09_Nantes-vs-Monaco
Processing: 2023-04-09_Lorient-vs-Marseille


Processing League: Bundesliga
Processing: 2023-02-04_Eintracht-Frankfurt-vs-Hertha-BSC
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Bochum-vs-Hoffenheim
    Inconsistent array length construction. Match ignored
Processing: 2023-02-04_Koln-vs-RB-Leipzig
Processing: 2023-02-04_Dortmund-vs-Freiburg
    Failed. Somehow.
Processing: 2023-02-04_Union-Berlin-vs-Mainz-05
Processing: 2023-02-04_Monchengladbach-vs-Schalke-04
    Inconsistent array length construction. Match ignored
Processing: 2023-02-05_Stuttgart-vs-Werder-Bremen
    Inconsistent array length construction. Match ignored

In [ ]:
dataset["Home Result", "----", "Win"] = (dataset.loc[:, pd.IndexSlice["Home", "----", "Score"]] > dataset.loc[:, pd.IndexSlice["Away", "----", "Score"]]).apply(lambda x: 1 if x is True else 0)
dataset["Home Result", "----", "Draw"] = (dataset.loc[:, pd.IndexSlice["Home", "----", "Score"]] == dataset.loc[:, pd.IndexSlice["Away", "----", "Score"]]).apply(lambda x: 1 if x is True else 0)
dataset["Home Result", "----", "Lost"] = (dataset.loc[:, pd.IndexSlice["Home", "----", "Score"]] < dataset.loc[:, pd.IndexSlice["Away", "----", "Score"]]).apply(lambda x: 1 if x is True else 0)

In [ ]:
print(dataset.shape)
X, y = dataset.iloc[:, :-5], dataset.iloc[:, -5:]

(362, 467)

In [ ]:
print(X.shape)
print(y.shape)

(362, 462)
(362, 5)

In [ ]:
dataset.to_csv("test.csv")
dataset.to_pickle("test.pickle")
dataset.to_parquet("test.parquet")
# dataset.to_feather("test.feather")

In [ ]:
%timeit pd.read_csv('test.csv')
%timeit pd.read_pickle('test.pickle')
%timeit pd.read_parquet('test.parquet')

24 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
879 µs ± 21.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
48.6 ms ± 803 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
!ls -GFlash test.csv test.pickle test.parquet

 36K -rw-r--r-- 1 root  36K Jan 31 13:34 test.csv
480K -rw-r--r-- 1 root 479K Jan 31 13:34 test.parquet
 40K -rw-r--r-- 1 root  40K Jan 31 13:34 test.pickle

In [ ]:
%timeit pd.read_csv('test.csv')
%timeit pd.read_pickle('test.pickle')
%timeit pd.read_parquet('test.parquet')

52.1 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.3 ms ± 144 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
65.7 ms ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
!ls -GFlash test.csv test.pickle test.parquet

580K -rw-r--r-- 1 root 577K Apr  1 16:39 test.csv
676K -rw-r--r-- 1 root 675K Apr  1 16:39 test.parquet
992K -rw-r--r-- 1 root 991K Apr  1 16:39 test.pickle

## Feature Engineering

In [ ]:
def process_position(df):
    _df = df.copy()
    teams = ["Home", "Away"]
    numbered_player_cols = ["Player_"+f"{i}".zfill(2) for i in range(1, 11+1)]
    pos_cols = [f"Pos_{pos}" for pos in POSITION_CHOICES]

    for team in teams:
        for player in numbered_player_cols:
            _pos = _df.loc[:, pd.IndexSlice[team, player, "Pos"]].apply(lambda x: x.split(","))
            _pos_label = position_mlb.fit_transform(_pos)
            for idx, pos in enumerate(POSITION_CHOICES):
                df.loc[:, (team, player, f"Pos_{pos}")] = _pos_label[:, idx]
    
    _df_home = df.loc[:, pd.IndexSlice["Home", :, :]].sort_index(level="Player", axis=1, sort_remaining=False)
    _df_away = df.loc[:, pd.IndexSlice["Away", :, :]].sort_index(level="Player", axis=1, sort_remaining=False)
    df = pd.concat([_df_home, _df_away], axis=1)
    df = df.drop(columns="Pos", axis=1, level=2)
    return df

# X.loc[:, pd.IndexSlice["Home", :, ["Pos"]+pos_cols]].sort_index(level="Player", axis=1, sort_remaining=False)
# X.drop(columns="Pos", axis=1, level=2)

In [ ]:
X_preprocessed = process_position(X)

<ipython-input-52-1a5bbea5c14d>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[:, (team, player, f"Pos_{pos}")] = _pos_label[:, idx]

In [ ]:
X_preprocessed

Club                              Home                             \
Player                       Player_01
Statistic keeper - Performance - Save% keeper - Performance - CS%
0                                  0.0                        0.0
1                                  0.0                        0.0
2                                  0.0                        0.0
3                                  0.0                        0.0
4                                  0.0                        0.0
..                                 ...                        ...
357                                0.0                        0.0
358                                0.0                        0.0
359                                0.0                        0.0
360                                0.0                        0.0
361                                0.0                        0.0

Club                                                                    \
Player
Statistic keeper_adv - Expected - PSxG/SoT keeper_adv - Expected - /90
0                                      0.0                         0.0
1                                      0.0                         0.0
2                                      0.0                         0.0
3                                      0.0                         0.0
4                                      0.0                         0.0
..                                     ...                         ...
357                                    0.0                         0.0
358                                    0.0                         0.0
359                                    0.0                         0.0
360                                    0.0                         0.0
361                                    0.0                         0.0

Club                                                               \
Player
Statistic shooting - Standard - SoT% shooting - Standard - SoT/90
0                               47.6                         1.76
1                               25.0                         0.40
2                               39.5                         1.30
3                               50.0                         0.42
4                               31.8                         0.64
..                               ...                          ...
357                             30.0                         0.34
358                             37.5                         0.63
359                             51.9                         1.72
360                             44.1                         0.68
361                             41.2                         0.87

Club                                                              \
Player
Statistic shooting - Standard - G/SoT shooting - Expected - G-xG
0                                0.20                       -1.4
1                                0.33                       -1.0
2                                0.33                       -1.3
3                                0.00                       -0.2
4                                0.29                       -0.5
..                                ...                        ...
357                              0.67                        0.4
358                              0.22                       -1.2
359                              0.30                       -1.5
360                              0.47                        1.3
361                              0.43                        0.8

Club                                  ...      Away                       \
Player                                ... Player_11
Statistic passing - xAG passing - xA  ...    Pos_MF Pos_DM Pos_CM Pos_LM
0                   0.2          0.3  ...         0      0      0      0
1                   0.3          0.2  ...         0      0      0      0
2                   1.4          1.5  ...         0      0      0      0
3                   0.4          0.5  ...         0      0      0      0
4                   1.0          0.6  ...         0      0      0      0
..                  ...          ...  ...       ...    ...    ...    ...
357                 1.4          1.6  ...         0      0      0      0
358                 1.5          1.3  ...         0      0      0      0
359                 3.5          1.6  ...         0      0      0      0
360                 2.3          2.6  ...         0      0      0      0
361                 0.3          0.4  ...         0      0      0      0

Club
Player
Statistic Pos_RM Pos_WM Pos_AM Pos_FW Pos_LW Pos_RW
0              0      0      0      0      0      0
1              0      0      0      0      0      0
2              0      0      0      0      0      0
3              0      0      0      0      0      0
4              0      0      0      0      0      0
..           ...    ...    ...    ...    ...    ...
357            0      0      0      0      0      0
358            0      0      0      0      0      0
359            0      0      0      0      0      0
360            0      0      0      0      0      0
361            0      0      0      0      0      0

[362 rows x 814 columns]

In [ ]:
X_preprocessed.to_csv("test_preprocessed.csv")
X_preprocessed.to_pickle("test_preprocessed.pickle")
X_preprocessed.to_parquet("test_preprocessed.parquet")

In [ ]:
%timeit pd.read_csv('test_preprocessed.csv')
%timeit pd.read_pickle('test_preprocessed.pickle')
%timeit pd.read_parquet('test_preprocessed.parquet')

118 ms ± 25.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.52 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
71.5 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
!ls -GFlash test.csv test.pickle test.parquet

ls: cannot access 'test.csv': No such file or directory
ls: cannot access 'test.pickle': No such file or directory
ls: cannot access 'test.parquet': No such file or directory

In [ ]:
%timeit pd.read_csv('test_preprocessed.csv')
%timeit pd.read_pickle('test_preprocessed.pickle')
%timeit pd.read_parquet('test_preprocessed.parquet')

118 ms ± 24.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.51 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
71.4 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
!ls -GFlash test_preprocessed.csv test_preprocessed.pickle test_preprocessed.parquet

1000K -rw-r--r-- 1 root  999K Apr 12 20:34 test_preprocessed.csv
1016K -rw-r--r-- 1 root 1014K Apr 12 20:34 test_preprocessed.parquet
 2.3M -rw-r--r-- 1 root  2.3M Apr 12 20:34 test_preprocessed.pickle

In [ ]:
df_preprocessed = pd.concat([X_preprocessed, y], axis=1)

## Save Data

In [ ]:
print(dataset.iloc[:3, -5:])
print(df_preprocessed.iloc[:3, -5:])

Club       Home  Away Home Result
Player     ----  ----        ----
Statistic Score Score         Win Draw Lost
0             3     2           1    0    0
1             1     0           1    0    0
2             1     1           0    1    0
Club       Home  Away Home Result
Player     ----  ----        ----
Statistic Score Score         Win Draw Lost
0             3     2           1    0    0
1             1     0           1    0    0
2             1     1           0    1    0

In [ ]:
dataset.to_parquet(f"{TRANSFORM_DIR}/data_for_ml.parquet")

In [ ]:
df_preprocessed.to_parquet(f"{TRANSFORM_DIR}/preprocessed_data_for_ml.parquet")

In [ ]:
__df = df_preprocessed.copy()

In [ ]:
__df.to_csv("test.csv")
__df.to_pickle("test.pickle")
__df.to_parquet("test.parquet")

In [ ]:
%timeit pd.read_csv('test.csv')
%timeit pd.read_pickle('test.pickle')
%timeit pd.read_parquet('test.parquet')

/usr/local/lib/python3.8/dist-packages/IPython/core/magics/execution.py:169: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819) have mixed types.Specify dtype option on import or set low_memory=False.
  timing = self.inner(it, self.timer)

2.86 s ± 26.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
55.8 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
222 ms ± 69.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash test.csv test.pickle test.parquet

 71M -rw-r--r-- 1 root  71M Jan 31 13:53 test.csv
988K -rw-r--r-- 1 root 986K Jan 31 13:53 test.parquet
169M -rw-r--r-- 1 root 169M Jan 31 13:53 test.pickle

In [ ]:
pd.read_parquet('test_preprocessed.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Columns: 814 entries, ('Home', 'Player_01', 'keeper - Performance - Save%') to ('Away', 'Player_11', 'Pos_RW')
dtypes: float64(440), int64(374)
memory usage: 1.7 MB

## Construct Table Reference

In [ ]:
import os

In [ ]:
LEAGUES = ["Premier-League", "Serie-A", "La-Liga", "Ligue-1", "Bundesliga"]

_df_main = pd.DataFrame()

for liga in LEAGUES:
    # if liga != "Premier-League":
    #     continue
    _teams_recorded = []
    files = []
    data_DIR = os.path.join(DATA_DIR, f"raw/{liga}/2022-2023_Matches/")

    for filename in os.listdir(data_DIR):
        if filename.endswith('csv'):
            files.append(filename)

    # csvfile = '2023-04-03_Everton-vs-Tottenham-Hotspur.csv'
    for csvfile in np.sort(files)[::-1][:20]:
        _df_test = pd.read_csv(os.path.join(data_DIR, csvfile), index_col=0, header=[0, 1, 2])
        teams = csvfile.split("_")[1].split(".csv")[0]
        home = teams.split("-vs-")[0]
        away = teams.split("-vs-")[1]
        for team in [home, away]:
            if team in _teams_recorded:
                continue
            _df_team = _df_test.loc[:, pd.IndexSlice[team]]
            for player in _df_team.columns.get_level_values(level="Player").unique():
                _df_player = _df_team.loc[:, pd.IndexSlice[player]]
                _df_player = _df_player.assign(player=player)
                _df_main = pd.concat([_df_main, _df_player], axis=0)
            _teams_recorded.append(team)

_df_main = _df_main.reset_index(drop=True)
non_player_cols = _df_main.columns.tolist()
non_player_cols.remove("player")
cols = ["player"] + np.sort(non_player_cols).tolist()
_df_main.columns.names = [""]
_df_main = _df_main[cols]
_df_main.to_csv(os.path.join(TRANSFORM_DIR, "player_references_leagues.csv"))
# _df_main.to_csv(os.path.join(TRANSFORM_DIR, "player_references.csv"))

In [ ]:
_df_main

,player,defense - 90s,defense - Age,defense - Blocks - Blocks,defense - Blocks - Pass,defense - Blocks - Sh,defense - Challenges - Att,defense - Challenges - Lost,defense - Challenges - Tkl,defense - Challenges - Tkl%,...,standard - Performance - PK,standard - Performance - PKatt,standard - Playing Time - 90s,standard - Playing Time - MP,standard - Playing Time - Min,standard - Playing Time - Starts,standard - Pos,standard - Progression - PrgC,standard - Progression - PrgP,standard - Progression - PrgR
0,Adam Forshaw,1.8,31-185,3.0,3.0,0.0,6.0,5.0,1.0,16.7,...,0.0,0.0,1.8,NaN,159.0,2,MF,0.0,8.0,0.0
1,Archie Gray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,0.0,0,MF,0.0,0.0,0.0
2,Brenden Aaronson,23.8,22-171,39.0,36.0,3.0,39.0,27.0,12.0,30.8,...,0.0,0.0,23.8,NaN,2144.0,26,"MF,FW",40.0,79.0,134.0
3,Cody Drameh,0.8,21-124,0.0,0.0,0.0,3.0,1.0,2.0,66.7,...,0.0,0.0,0.8,NaN,69.0,1,DF,0.0,2.0,3.0
4,Crysencio Summerville,12.3,21-163,15.0,13.0,2.0,17.0,9.0,8.0,47.1,...,0.0,0.0,12.3,NaN,1108.0,10,FW,46.0,36.0,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,Nick Pope,28.2,30-357,0.0,0.0,0.0,3.0,2.0,1.0,33.3,...,0.0,0.0,28.2,29.0,2541.0,29,GK,0.0,1.0,0.0
693,Paul Dummett,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0,DF,0.0,0.0,0.0
694,Ryan Fraser,3.5,29-046,3.0,2.0,1.0,5.0,3.0,2.0,40.0,...,0.0,0.0,3.5,8.0,313.0,3,FW,8.0,9.0,23.0
695,Sean Longstaff,24.9,25-163,33.0,26.0,7.0,50.0,32.0,18.0,36.0,...,0.0,0.0,24.9,29.0,2242.0,25,MF,21.0,109.0,97.0
696,Sven Botman,25.7,23-089,36.0,19.0,17.0,23.0,6.0,17.0,73.9,...,0.0,0.0,25.7,27.0,2317.0,26,DF,7.0,66.0,3.0

In [ ]:
_df = pd.read_csv(os.path.join(TRANSFORM_DIR, "player_references_five_leagues.csv"), index_col=0)
_df

,player,defense - 90s,defense - Age,defense - Blocks - Blocks,defense - Blocks - Pass,defense - Blocks - Sh,defense - Challenges - Att,defense - Challenges - Lost,defense - Challenges - Tkl,defense - Challenges - Tkl%,...,standard - Performance - PK,standard - Performance - PKatt,standard - Playing Time - 90s,standard - Playing Time - MP,standard - Playing Time - Min,standard - Playing Time - Starts,standard - Pos,standard - Progression - PrgC,standard - Progression - PrgP,standard - Progression - PrgR
0,Adam Forshaw,1.8,31-185,3.0,3.0,0.0,6.0,5.0,1.0,16.7,...,0.0,0.0,1.8,NaN,159.0,2,MF,0.0,8.0,0.0
1,Archie Gray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,0.0,0,MF,0.0,0.0,0.0
2,Brenden Aaronson,23.8,22-171,39.0,36.0,3.0,39.0,27.0,12.0,30.8,...,0.0,0.0,23.8,NaN,2144.0,26,"MF,FW",40.0,79.0,134.0
3,Cody Drameh,0.8,21-124,0.0,0.0,0.0,3.0,1.0,2.0,66.7,...,0.0,0.0,0.8,NaN,69.0,1,DF,0.0,2.0,3.0
4,Crysencio Summerville,12.3,21-163,15.0,13.0,2.0,17.0,9.0,8.0,47.1,...,0.0,0.0,12.3,NaN,1108.0,10,FW,46.0,36.0,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3386,Suat Serdar,19.3,26-000,47.0,35.0,12.0,35.0,17.0,18.0,51.4,...,0.0,0.0,19.3,26.0,1736.0,22,MF,29.0,68.0,44.0
3387,Tjark Ernst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0,GK,0.0,0.0,0.0
3388,Tolga Ciğerci,6.7,31-019,5.0,3.0,2.0,15.0,6.0,9.0,60.0,...,0.0,0.0,6.7,9.0,602.0,8,MF,3.0,29.0,2.0
3389,Vladimír Darida,0.3,32-246,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.3,3.0,31.0,0,MF,1.0,0.0,1.0
3390,Wilfried Kanga,15.0,25-049,12.0,9.0,3.0,3.0,1.0,2.0,66.7,...,0.0,0.0,15.0,21.0,1352.0,15,FW,10.0,11.0,71.0

In [ ]:
_df_main.player.to_list()

#### Fixing Problems

- Duplicates

In [ ]:
problem = ["Wesley Fofana", "Morgan Gibbs White", "Albert Sambi Lokonga", "Jonjo Shelvey", "Jorginho"]

# maybe just aggregate by adding each attribute